# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/io_plan.xdc

# IP: ip/openram12/openram12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==openram12 || ORIG_REF_NAME==openram12} -quiet] -quiet

# IP: ip/openram8/openram8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==openram8 || ORIG_REF_NAME==openram8} -quiet] -quiet

# IP: ip/closeram8/closeram8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==closeram8 || ORIG_REF_NAME==closeram8} -quiet] -quiet

# IP: ip/mapram1_1/mapram1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mapram1 || ORIG_REF_NAME==mapram1} -quiet] -quiet
