# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/01Astar/Astar128x128/top_astargnps/top_astargnps.srcs/sources_1/ip/closeram8/closeram8.xci
# IP: The module: 'closeram8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/01Astar/Astar128x128/top_astargnps/top_astargnps.srcs/sources_1/ip/closeram8/closeram8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'closeram8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/01Astar/Astar128x128/top_astargnps/top_astargnps.srcs/sources_1/ip/closeram8/closeram8.xci
# IP: The module: 'closeram8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/01Astar/Astar128x128/top_astargnps/top_astargnps.srcs/sources_1/ip/closeram8/closeram8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'closeram8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
